version: '3.8'

services:
  # 1. The Message Broker
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 2. The FastAPI Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    # The command to start FastAPI (bound to 0.0.0.0 so it can communicate outside the container)
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./chroma_db:/app/chroma_db # Saves your vector database to your hard drive so it isn't deleted on restart

  # 3. The AI Engine
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    # The command to start Celery
    command: celery -A app.celery_worker.celery_app worker --loglevel=info --pool=solo
    volumes:
      - ./chroma_db:/app/chroma_db

  # 4. The User Interface
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api